# Generated by Django 4.2.23 on 2025-08-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("authors", models.CharField(max_length=512)),
                ("title", models.CharField(max_length=512)),
                ("journal", models.CharField(blank=True, max_length=512)),
                (
                    "citation",
                    models.CharField(
                        blank=True, help_text="Volume, issue and pages", max_length=512
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("doi", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["-year", "authors"],
            },
        ),
    ]
