# Generated by Django 4.2.23 on 2025-08-05 11:38

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('now', '0002_publication_extra_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='doi',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['IGNORECASE'], message='Enter a valid DOI.', regex='^10\\.\\d{4,9}/[-._;()/:A-Z0-9]+$')]),
        ),
    ]
